# -*- coding: utf-8 -*-
"""Data Cleaning Code_Vaishnavi and Purva_Data Visualization Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oqzcY-kQKSf2s5vmk953_KUvZKq9LJhB
"""

# This code was executed on local machine i.e. on VSCODE where path of the CSV file is given and finally the cleaned CSV file was generated after execution of this code

import pandas as pd

# Load the CSV file into a DataFrame
file_path = 'C:\\Users\\Vaishnavi\\Documents\\Rates_and_Trends_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults__35___by_County__Age_Group__Race_Ethnicity__and_Sex___2000-2019.csv'
df = pd.read_csv(file_path)

# Display the initial information about the dataset
print("Initial Dataset Info:")
print(df.info())

# Handling missing values in the 'Data_Value' column
df = df.dropna(subset=['Data_Value'])

# Removing duplicates based on all columns
df = df.drop_duplicates()

# Display the intermediate results
print("\nIntermediate Dataset Info:")
print(df.info())

# Save the cleaned dataset to a new CSV file
cleaned_file_path = 'cleaned_dataset.csv'
df.to_csv(cleaned_file_path, index=False)

print(f"\nCleaned dataset saved to {cleaned_file_path}")

uploaded = files.upload()

uploaded = files.upload()

uploaded = files.upload()

uploaded = files.upload()

uploaded = files.upload()

"""# Uncleaned Dataset"""

from IPython.display import Image
Image('ss1.png', width=1500)

"""# Execution Of Code In VSCODE"""

from IPython.display import Image
Image('ss2.png', width=1500)

"""# Output Of Cleaning Process"""

from IPython.display import Image
Image('ss3.png', width=1500)

from IPython.display import Image
Image('ss4.png', width=1500)

"""# Generation Of Cleaned Dataset CSV file after Successful Execution Of CODE"""

from IPython.display import Image
Image('ss5.png', width=1500)